### ISSUE TITLE
scheme is not handled in _parse_settings

### ISSUE THREAD

**Issue by willfixlater** [ajkavanagh/pyramid_jwtauth#10]
I can't set scheme in my .ini because the _parse_settings function doesn't recognise it. Is there any specific reason for this or is that a bug?

I am using a fork with a patch ATM, so I can make a pull request if that suits you. But it might be easier just to drop the line in.

**Comment by ajkavanagh** [comment]
It's almost certainly a bug.  `scheme` was added via a PR and I didn't check to see if it could be set via the `ini` file.  Please do submit a PR.  Thanks very much!

**Comment by willfixlater** [comment]
Pull request submitted:
https://github.com/ajkavanagh/pyramid_jwtauth/pull/11

**Comment by ajkavanagh** [comment]
Fixed by #11.  Bumped version to 0.1.3 on PiPy and pushed.  Thanks for PR.
