### ISSUE TITLE
Incorrect scheme used in Auhorization header

### ISSUE THREAD

**Issue by wichert** [ajkavanagh/pyramid_jwtauth#5]
The standard (or at least very common) scheme for JWT tokens in the Authorization header is `Bearer`. Unfortunately this package uses `JWT`, which makes it incompatible with standard clients. Can you make the scheme to use configurable?

**Comment by ajkavanagh** [comment]
Sorry for the delay on getting this merged.  I've been away plus had a horrible deadline at work.
